# Generated by Django 5.2.14 on 2026-05-26 10:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="Nexus Warehouse", max_length=200),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="brand/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD – United States Dollar", max_length=100
                    ),
                ),
                (
                    "timezone",
                    models.CharField(default="(GMT+00:00) UTC", max_length=100),
                ),
                (
                    "language",
                    models.CharField(default="English (United States)", max_length=100),
                ),
                ("date_format", models.CharField(default="MM/DD/YYYY", max_length=20)),
                ("theme", models.CharField(default="light", max_length=10)),
                (
                    "default_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
