# Generated by Django 5.2.14 on 2026-05-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="currency",
            field=models.CharField(default="GHS – Ghanaian Cedi", max_length=100),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="date_format",
            field=models.CharField(default="DD/MM/YYYY", max_length=20),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="timezone",
            field=models.CharField(default="(GMT+00:00) Africa/Accra", max_length=100),
        ),
    ]
