# Generated by Django 4.2.10 on 2026-06-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_transfernotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfernotification",
            name="from_branch_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="transfernotification",
            name="transfer_pk",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
