# Generated by Django 4.2.10 on 2026-07-13 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
        ("dispatch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchorder",
            name="assigned_driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispatches",
                to="fleet.driver",
            ),
        ),
        migrations.AddField(
            model_name="dispatchorder",
            name="assigned_vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispatches",
                to="fleet.vehicle",
            ),
        ),
    ]
