# Generated by Django 4.2.17 on 2026-05-28 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dispatch", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("customer_return", "Customer Return"),
                            ("damaged_transit", "Damaged in Transit"),
                            ("wrong_item", "Wrong Item"),
                            ("expired", "Expired"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "return_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Return"),
                            ("partial", "Partial Return"),
                        ],
                        default="full",
                        max_length=10,
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("restock", "Restock"),
                            ("quarantine", "Quarantine"),
                            ("dispose", "Dispose"),
                            ("return_supplier", "Return to Supplier"),
                        ],
                        default="restock",
                        max_length=20,
                    ),
                ),
                ("return_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dispatch.dispatchorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("damaged", "Damaged"),
                            ("pristine", "Pristine"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.product",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="returns.returnrequest",
                    ),
                ),
            ],
        ),
    ]
