# Generated by Django 4.2.17 on 2026-05-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sourced_from_branch",
            field=models.CharField(
                blank=True,
                help_text="Branch code this stock was transferred from",
                max_length=20,
                null=True,
            ),
        ),
    ]
