# Generated by Django 4.2.17 on 2026-05-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransfer",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="reference",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
