# Generated by Django 4.2.10 on 2026-07-13 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0002_alter_driver_user_alter_proofofdelivery_delivered_by"),
        (
            "transfers",
            "0002_stocktransfer_completed_at_stocktransfer_reference_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransfer",
            name="assigned_driver",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers",
                to="fleet.driver",
            ),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="assigned_vehicle",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers",
                to="fleet.vehicle",
            ),
        ),
    ]
