# Generated by Django 4.2.10 on 2026-07-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0003_stocktransfer_assigned_driver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("in_transit", "In Transit"),
                    ("received", "Received"),
                    ("complete", "Complete"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
